Repository eureca-final-capstone-project/front-module, pull requests merged in 2025-07, with the labels that each got.

#10 [VT2-136] feat: 탭 컴포넌트 구현
  package-lock.json
  package.json
  src/components/Tabs/Tabs.tsx
  src/hooks/useDeviceType.ts
  src/index.css
  src/pages/MyPage.tsx
  src/pages/MyPage/DataChargePage.tsx
  src/pages/MyPage/EventCouponPage.tsx
  src/pages/MyPage/FavoritesPage.tsx
  src/pages/MyPage/PayHistoryPage.tsx
  src/pages/MyPage/ReportHistoryPage.tsx
  src/pages/MyPage/TransactionHistoryPage.tsx
  src/pages/MyPage/index.tsx
  src/router/index.tsx
Labels: enhancement, stlye

#11 [VT2-137] feat: 카드 컴포넌트 구현
  src/assets/icons/arrowRightIcon.svg
  src/assets/icons/noticeIcon.svg
  src/assets/icons/warningIcon.svg
  src/components/Card/Card.tsx
  src/index.css
  src/pages/PayChargeResultPage.tsx
  src/router/index.tsx
  src/svg.d.ts
  vite.config.ts
Labels: enhancement, stlye

#13 [VT2-139] feat: 리스트 타일 컴포넌트 구현
  src/components/Animation/FadeInUpDiv.tsx
  src/components/ListTile/ListTile.tsx
  src/index.css
  src/pages/MyPage/PayHistoryPage.tsx
  src/pages/MyPage/index.tsx
Labels: enhancement, stlye

#14 [VT2-174] feat: 토스트 컴포넌트 구현
  package-lock.json
  package.json
  src/assets/icons/toast-error.svg
  src/assets/icons/toast-success.svg
  src/components/Toast/Toast.stories.tsx
  src/components/Toast/Toast.tsx
  src/hooks/useToast.ts
  src/index.css
  src/main.tsx
Labels: enhancement, stlye

#16 [VT2-143] refactor: 뱃지 컴포넌트 리팩토링
  package-lock.json
  package.json
  src/components/Badge/Badge.stories.tsx
  src/components/Badge/Badge.tsx
  src/components/Badge/badgeVariants.ts
  src/utils/cn.ts
Labels: chore, style, refactor

#17 [VT2-130] feat: 검색바 컴포넌트 구현
  src/assets/icons/search.svg
  src/components/SearchBar/SearchBar.tsx
Labels: feat, style

#21 [VT2-138] feat: 영수증 모달 컴포넌트 구현
  src/assets/icons/arrow-right.svg
  src/assets/icons/circle-check.svg
  src/assets/icons/notice.svg
  src/assets/icons/warning.svg
  src/assets/icons/x.svg
  src/components/Card/Card.tsx
  src/components/ReceiptModal/ChargeReceipt.tsx
  src/components/ReceiptModal/ReceiptInfo.tsx
  src/components/ReceiptModal/ReceiptModal.tsx
  src/components/ReceiptModal/TradeReceipt.tsx
  src/components/ReceiptModal/config.ts
  src/index.css
  src/pages/MyPage/ReportHistoryPage.tsx
Labels: feat, style

#23 [VT2-141] feat: EventCoupon 컴포넌트 구현
  src/apis/eventCoupon.ts
  src/assets/images/kakao-pay.svg
  src/assets/images/naver-pay.svg
  src/assets/images/toss-pay.png
  src/index.css
  src/mocks/eventData.ts
  src/pages/MyPage/EventCouponPage.tsx
  src/pages/MyPage/components/EventCoupon/EventCoupon.tsx
Labels: feat, style

#24 [VT2-97] feat: 헤더 컴포넌트 구현
  src/assets/icons/menu.svg
  src/assets/icons/notification-active.svg
  src/assets/icons/notification.svg
  src/components/Header/Header.tsx
  src/components/Header/HeaderNav.tsx
  src/components/SearchBar/SearchBar.tsx
  src/layout/DefaultLayout.tsx
Labels: feat, style

#25 [VT2-140] feat: Data Voucher 컴포넌트 구현
  src/components/Animation/FadeInUpMotion.tsx
  src/components/Animation/ScaleDownMotion.tsx
  src/pages/MyPage/DataChargePage.tsx
  src/pages/MyPage/PayHistoryPage.tsx
  src/pages/MyPage/components/DataChargeVoucher/DataChargeVoucher.tsx
Labels: chore, feat, style

#26 [VT2-94] feat: WebMobileLayout 구현
  src/assets/icons/back.svg
  src/components/Container/Container.tsx
  src/components/Header/Header.tsx
  src/layout/DefaultLayout.tsx
  src/layout/WebMobileLayout.tsx
  src/pages/WritePage.tsx
  src/router/index.tsx
Labels: feat, style

#27 [VT2-100] style: Input 컴포넌트 suffix, prefix 스타일 수정
  src/components/Input/Input.tsx
Labels: style

#30 [VT2-142] feat: PostCard 컴포넌트 구현
  src/assets/icons/datcha-coin-secondary.svg
  src/assets/icons/heart-fill.svg
  src/assets/icons/heart.svg
  src/assets/images/test-image.png
  src/components/Badge/Badge.tsx
  src/components/PostCard/PostCard.stories.tsx
  src/components/PostCard/PostCard.tsx
  src/components/PostCard/PostCardCol.tsx
  src/components/PostCard/PostCardRow.tsx
  src/components/PostCard/ProviderBadge.tsx
Labels: feat, style

#29 [VT2-240] feat: 마이페이지 상단 레이아웃 구현
  src/assets/icons/datcha-coin-color.svg
  src/components/Button/Button.tsx
  src/components/ListTile/ListTile.tsx
  src/components/Tabs/Tabs.tsx
  src/pages/MyPage/PayHistoryPage.tsx
  src/pages/MyPage/components/InfoCard/DataStatus.tsx
  src/pages/MyPage/components/InfoCard/InfoCard.tsx
  src/pages/MyPage/components/InfoCard/PayStatus.tsx
  src/pages/MyPage/components/InfoCard/Profile.tsx
  src/pages/MyPage/index.tsx
  src/utils/format.ts
Labels: feat, style, refactor

#33 [VT2-155] feat: 로그인 토큰 관리
  package-lock.json
  src/apis/client.ts
  src/apis/interceptors.ts
  src/pages/LoginPage/components/LoginForm.tsx
  src/store/authStore.ts
Labels: feat

#34 [VT2-163] feat: 소셜 로그인 적용
  src/apis/auth.ts
  src/assets/icons/google-login.svg
  src/assets/icons/kakao-login.svg
  src/assets/icons/naver-login.svg
  src/layout/AuthLayout.tsx
  src/pages/LoginPage/components/SocialLogin.tsx
  src/pages/LoginPage/index.tsx
Labels: feat

#38 [VT2-226] feat: 관심거래 삭제 리스트 반영
  src/hooks/useModal.ts
  src/hooks/useSelect.ts
  src/pages/MyPage/FavoritesPage.tsx
  src/pages/MyPage/components/ButtonHeader/ButtonHeader.tsx
Labels: feat, refactor

#37 [VT2-138] feat: 영수증 모달 애니메이션 구현
  src/components/ReceiptModal/ChargeReceipt.tsx
  src/components/ReceiptModal/ReceiptModal.tsx
  src/components/ReceiptModal/TradeReceipt.tsx
  src/index.css
  src/pages/MyPage/ReportHistoryPage.tsx
Labels: fix, feat

#39 [VT2-225] feat: 회원가입 페이지 구현
  src/apis/auth.ts
  src/assets/icons/password-off.svg
  src/components/DropDown/DropDown.tsx
  src/components/Input/Input.tsx
  src/constants/agreements.ts
  src/constants/carrier.ts
  src/index.css
  src/layout/AuthLayout.tsx
  src/pages/LoginPage/components/LoginForm.tsx
  src/pages/LoginPage/index.tsx
  src/pages/SignUpPage/components/Agreement.tsx
  src/pages/SignUpPage/components/SignUpForm.tsx
  src/pages/SignUpPage/index.tsx
  src/router/index.tsx
  src/types/auth.ts
  src/utils/format.ts
  src/utils/validation.ts
Labels: feat, style

#40 [VT2-163] feat: OAuth 임시 토큰 추출 및 로그인 처리
  src/apis/auth.ts
  src/apis/interceptors.ts
  src/pages/LoginPage/OAuthCallbackPage.tsx
  src/router/index.tsx
Labels: feat

#42 [VT2-142] refactor: PostCard 컴포넌트 수정
  src/components/Modal/Modal.tsx
  src/components/PostCard/PostCard.stories.tsx
  src/components/PostCard/PostCard.tsx
  src/components/PostCard/PostCardCol.tsx
  src/components/PostCard/PostCardRow.tsx
  src/components/Toast/Toast.tsx
  src/constants/imageData.ts
  src/mocks/postData.ts
  src/pages/MyPage/FavoritesPage.tsx
Labels: style, refactor

#43 [VT2-225] feat: OAuth 신규 사용자 추가 정보 입력 페이지 구현
  src/apis/auth.ts
  src/layout/AuthLayout.tsx
  src/pages/SignUpPage/AdditionalInfoPage.tsx
  src/pages/SignUpPage/components/AddtionalInfoForm.tsx
  src/router/index.tsx
  src/types/auth.ts
  src/utils/validation.ts
Labels: feat, style

#48 [VT2-91] feat: 관리자 페이지 레아아웃 구현
  src/assets/icons/active-bar.svg
  src/assets/icons/admin.svg
  src/assets/icons/dashboard.svg
  src/assets/icons/logout.svg
  src/assets/icons/report.svg
  src/assets/icons/restriction.svg
  src/assets/icons/user.svg
  src/constants/adminMenu.ts
  src/layout/AdminLayout.tsx
  src/pages/AdminPage/Dashboard.tsx
  src/pages/AdminPage/components/Sidebar.tsx
  src/router/index.tsx
Labels: feat, style

#50 [VT2 237] feat: 사용자 데이터 현황 조회 API 연동
  src/apis/userInfo.ts
  src/pages/ChangeDataPage.tsx
  src/pages/MyPage/components/InfoCard/DataStatus.tsx
  src/router/index.tsx
Labels: feat

#51 [VT2-227] feat: 데이터 충전권 API 연동
  src/apis/dataVoucher.ts
  src/components/Animation/ScaleDownMotion.tsx
  src/pages/MyPage/DataChargePage.tsx
  src/pages/MyPage/components/DataChargeVoucher/DataChargeVoucher.tsx
  src/pages/MyPage/components/InfoCard/Profile.tsx
  src/utils/telecom.ts
Labels: feat, refactor
