Repository eureca-final-capstone-project/front-module, pull requests merged in 2025-08, with the labels that each got.

#180 [VT2-485] refactor: 메인페이지 및 서비스 가이드 페이지 리팩토링
  src/assets/icons/basket.svg
  src/assets/icons/cart.svg
  src/assets/images/hero.png
  src/pages/GuidePage/index.tsx
  src/pages/MainPage/components/LatestSection.tsx
  src/pages/MainPage/components/RecommendSection.tsx
Labels: style, refactor

#181 [VT2-485] fix: 로그인 멘트 수정 및 웹 알림 중복 로직 제거
  src/components/AlertModal/AlertModal.tsx
  src/pages/LoginPage/components/LoginForm.tsx
Labels: fix

#182 [VT2-284] chore: 33차 배포
  src/assets/icons/basket.svg
  src/assets/icons/cart.svg
  src/assets/images/hero.png
  src/components/AlertModal/AlertModal.tsx
  src/pages/GuidePage/index.tsx
  src/pages/LoginPage/components/LoginForm.tsx
  src/pages/MainPage/components/LatestSection.tsx
  src/pages/MainPage/components/RecommendSection.tsx
  src/pages/PostEditPage/index.tsx
  src/pages/PostWritePage/index.tsx
Labels: chore
